### ISSUE TITLE
building c2tsv error: c2tsv.nim(7, 38) Error: cannot open file: cligen/osUt

### ISSUE THREAD

**Issue by liquidaty** [c-blake/nio#1]
On OSX. ran `brew install nim`. Then tried to follow readme instructions.
```
git clone https://github.com/c-blake/nio
cd nio
n="nim c -d:danger"
$n nio && $n utils/c2tsv && $n demo/tabGen &&
  install -cm755 nio utils/c2tsv demo/tabGen ~/bin
```

Got: `Error: cannot open file: cligen/osUt`

Any suggestions?

**Comment by c-blake** [comment]
I had said "something like". ;-)  Added `cligen` install to that description, though.  It should be more friendly to Nim newcomers, though.  Sorry for the incompleteness!

In terms of tuning the compilation to get performance in the output binary, you may also want `-d:danger` (as already listed) and  `--gc:arc`.   `--passC:-march=native` (for e.g., gcc) can vary C compiler backend optimizations.  With gcc you may want `-d:lto`.  You can edit your `$HOME/.config/nim.cfg` or `$HOME/.config/config.nims` configurations to add your own `-d:` switches.

Using PGO in gcc on `nim c` generated C code can often improve run-times by 1.5..2X, but then you need a "training data" set.  https://github.com/c-blake/nimsearch/blob/main/nim-pgo shows one way to set this up, but YMMV.  For `c2tsv` in particular, I have actually seen PGO *slow down* run-times -- even running on the *very same data* upon which the profile was built/trained.  All that extra measured data (loop counts, basic block arcs/jumps, etc.) induces less good application of optimization heuristics - a never impossible situation, but often overlooked. This worse-with-PGO-not-2X-better property can and does vary quite a bit from CPU family (Intel/AMD, M1, etc.) or even across generations of said family.

For reasons like these, I often say 1.5..2X speed changes on just 1 CPU are not so conclusive.  *Maaaybe* you really have knowledge/control over deployment as in some cloud settings. :)  Something that does generalize is that parsing numbers is much less efficient than operating upon pre-parsed binary..as much or more so than C compared to Python.  The overarching idea of this package is to stop "re-parsing" for some value of "re-". `c2tsv` is just a helper program for that.
